# Generated by Django 6.0.7 on 2026-07-18 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='stale_alert_sent',
            field=models.BooleanField(default=False),
        ),
    ]
