# Generated by Django 6.0.7 on 2026-07-22 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('braindump', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='braindump',
            name='ai_feedback',
            field=models.TextField(blank=True),
        ),
    ]
